from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_analysis(object):

    def setupUi(self, analysis):
        analysis.setObjectName('analysis')
        analysis.setEnabled(True)
        analysis.resize(381, 247)
        self.centralWidget = QtWidgets.QWidget(analysis)
        self.centralWidget.setObjectName('centralWidget')
        self.count = QtWidgets.QLabel(self.centralWidget)
        self.count.setGeometry(QtCore.QRect(290, 170, 81, 21))
        self.count.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.count.setObjectName('count')
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(200, 170, 81, 21))
        self.label_2.setObjectName('label_2')
        self.listWidget = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 171, 211))
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.listWidget.setDragEnabled(False)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setObjectName('listWidget')
        self.continue_2 = QtWidgets.QPushButton(self.centralWidget)
        self.continue_2.setGeometry(QtCore.QRect(220, 200, 113, 32))
        self.continue_2.setDefault(True)
        self.continue_2.setObjectName('continue_2')
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(190, 50, 181, 101))
        self.widget.setObjectName('widget')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName('verticalLayout')
        self.all = QtWidgets.QRadioButton(self.widget)
        self.all.setChecked(True)
        self.all.setObjectName('all')
        self.verticalLayout.addWidget(self.all)
        self.noblocked = QtWidgets.QRadioButton(self.widget)
        self.noblocked.setObjectName('noblocked')
        self.verticalLayout.addWidget(self.noblocked)
        self.blocked = QtWidgets.QRadioButton(self.widget)
        self.blocked.setObjectName('blocked')
        self.verticalLayout.addWidget(self.blocked)
        analysis.setCentralWidget(self.centralWidget)
        self.retranslateUi(analysis)
        QtCore.QMetaObject.connectSlotsByName(analysis)

    def retranslateUi(self, analysis):
        _translate = QtCore.QCoreApplication.translate
        analysis.setWindowTitle(_translate('analysis', 'analysis'))
        self.count.setText(_translate('analysis', '123456789'))
        self.label_2.setText(_translate('analysis', 'Количество:'))
        self.listWidget.setSortingEnabled(True)
        self.continue_2.setText(_translate('analysis', 'Продолжить'))
        self.all.setText(_translate('analysis', 'Все'))
        self.noblocked.setText(_translate('analysis', 'Не заблокированные'))
        self.blocked.setText(_translate('analysis', 'Заблокированные'))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    analysis = QtWidgets.QMainWindow()
    ui = Ui_analysis()
    ui.setupUi(analysis)
    analysis.show()
    sys.exit(app.exec_())
