# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'another.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_another(object):
    def setupUi(self, another):
        another.setObjectName("another")
        another.resize(361, 465)
        self.centralWidget = QtWidgets.QWidget(another)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 341, 311))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 31, 321, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.objectType = QtWidgets.QComboBox(self.layoutWidget)
        self.objectType.setObjectName("objectType")
        self.objectType.addItem("")
        self.objectType.addItem("")
        self.objectType.addItem("")
        self.objectType.addItem("")
        self.objectType.addItem("")
        self.objectType.addItem("")
        self.objectType.addItem("")
        self.objectType.addItem("")
        self.objectType.addItem("")
        self.objectType.addItem("")
        self.objectType.addItem("")
        self.objectType.addItem("")
        self.horizontalLayout.addWidget(self.objectType)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ownerID = QtWidgets.QLineEdit(self.layoutWidget)
        self.ownerID.setObjectName("ownerID")
        self.horizontalLayout_2.addWidget(self.ownerID)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.objectID = QtWidgets.QLineEdit(self.layoutWidget)
        self.objectID.setObjectName("objectID")
        self.horizontalLayout_3.addWidget(self.objectID)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.liked = QtWidgets.QCheckBox(self.layoutWidget)
        self.liked.setEnabled(True)
        self.liked.setText("")
        self.liked.setChecked(True)
        self.liked.setObjectName("liked")
        self.horizontalLayout_4.addWidget(self.liked)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.reposted = QtWidgets.QCheckBox(self.layoutWidget)
        self.reposted.setEnabled(True)
        self.reposted.setText("")
        self.reposted.setChecked(False)
        self.reposted.setObjectName("reposted")
        self.horizontalLayout_6.addWidget(self.reposted)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.commented = QtWidgets.QCheckBox(self.layoutWidget)
        self.commented.setEnabled(True)
        self.commented.setText("")
        self.commented.setChecked(False)
        self.commented.setObjectName("commented")
        self.horizontalLayout_7.addWidget(self.commented)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.likedComments = QtWidgets.QCheckBox(self.layoutWidget)
        self.likedComments.setEnabled(True)
        self.likedComments.setText("")
        self.likedComments.setChecked(False)
        self.likedComments.setObjectName("likedComments")
        self.horizontalLayout_8.addWidget(self.likedComments)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 400, 241, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_5.addWidget(self.cancel)
        self.continue_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.continue_2.setDefault(True)
        self.continue_2.setObjectName("continue_2")
        self.horizontalLayout_5.addWidget(self.continue_2)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser.setEnabled(False)
        self.textBrowser.setGeometry(QtCore.QRect(30, 330, 291, 61))
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setObjectName("textBrowser")
        another.setCentralWidget(self.centralWidget)

        self.retranslateUi(another)
        QtCore.QMetaObject.connectSlotsByName(another)

    def retranslateUi(self, another):
        _translate = QtCore.QCoreApplication.translate
        another.setWindowTitle(_translate("another", "another"))
        self.groupBox.setTitle(_translate("another", "Настройки"))
        self.label.setText(_translate("another", "Тип объекта"))
        self.objectType.setItemText(0, _translate("another", "Пост"))
        self.objectType.setItemText(1, _translate("another", "Фото"))
        self.objectType.setItemText(2, _translate("another", "Обсуждение"))
        self.objectType.setItemText(3, _translate("another", "Аудио"))
        self.objectType.setItemText(4, _translate("another", "Видео"))
        self.objectType.setItemText(5, _translate("another", "Заметка"))
        self.objectType.setItemText(6, _translate("another", "Товар"))
        self.objectType.setItemText(7, _translate("another", "Комментарий к посту"))
        self.objectType.setItemText(8, _translate("another", "Комментарий к фото"))
        self.objectType.setItemText(9, _translate("another", "Комментарий к видео"))
        self.objectType.setItemText(10, _translate("another", "Комментарий в обсуждении"))
        self.objectType.setItemText(11, _translate("another", "Комментарий к товару"))
        self.label_2.setText(_translate("another", "ID владельца*"))
        self.ownerID.setToolTip(_translate("another", "<html><head/><body><p>Добавьте &quot;-&quot; перед ID группы.</p></body></html>"))
        self.label_3.setText(_translate("another", "ID объекта"))
        self.objectID.setToolTip(_translate("another", "<html><head/><body><p>ID Like-объекта</p></body></html>"))
        self.label_4.setText(_translate("another", "Лайкнувшие"))
        self.label_5.setText(_translate("another", "Репостнувшие"))
        self.label_6.setText(_translate("another", "Комментировавшие"))
        self.label_7.setText(_translate("another", "Лайкнувшие комментарии"))
        self.cancel.setText(_translate("another", "Отмена"))
        self.continue_2.setText(_translate("another", "Продолжить"))
        self.textBrowser.setHtml(_translate("another", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:7pt;\">* Идентификатор владельца Like-объекта: id пользователя, id сообщества (со знаком «минус») или id приложения.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    another = QtWidgets.QMainWindow()
    ui = Ui_another()
    ui.setupUi(another)
    another.show()
    sys.exit(app.exec_())

