from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_details(object):

    def setupUi(self, details):
        details.setObjectName('details')
        details.resize(606, 307)
        self.centralWidget = QtWidgets.QWidget(details)
        self.centralWidget.setObjectName('centralWidget')
        self.table = QtWidgets.QTableWidget(self.centralWidget)
        self.table.setGeometry(QtCore.QRect(10, 10, 581, 291))
        self.table.setObjectName('table')
        self.table.setColumnCount(10)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(9, item)
        details.setCentralWidget(self.centralWidget)
        self.retranslateUi(details)
        QtCore.QMetaObject.connectSlotsByName(details)

    def retranslateUi(self, details):
        _translate = QtCore.QCoreApplication.translate
        details.setWindowTitle(_translate('details', 'details'))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate('details', 'Тип объекта'))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate('details', 'ID группы*'))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate('details', 'Токен группы*'))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate('details', 'Токен пользователя'))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate('details', 'Выбрать из'))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate('details', 'ID владельца*'))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate('details', 'ID объекта'))
        item = self.table.horizontalHeaderItem(7)
        item.setText(_translate('details', 'Действие'))
        item = self.table.horizontalHeaderItem(8)
        item.setText(_translate('details', 'Срок*'))
        item = self.table.horizontalHeaderItem(9)
        item.setText(_translate('details', 'Причина*'))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    details = QtWidgets.QMainWindow()
    ui = Ui_details()
    ui.setupUi(details)
    details.show()
    sys.exit(app.exec_())
