from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_group(object):

    def setupUi(self, group):
        group.setObjectName('group')
        group.resize(292, 274)
        self.centralWidget = QtWidgets.QWidget(group)
        self.centralWidget.setObjectName('centralWidget')
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 271, 191))
        self.groupBox.setObjectName('groupBox')
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 251, 151))
        self.layoutWidget.setObjectName('layoutWidget')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName('verticalLayout')
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName('label')
        self.horizontalLayout.addWidget(self.label)
        self.id = QtWidgets.QLineEdit(self.layoutWidget)
        self.id.setObjectName('id')
        self.horizontalLayout.addWidget(self.id)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName('label_2')
        self.horizontalLayout_2.addWidget(self.label_2)
        self.token = QtWidgets.QLineEdit(self.layoutWidget)
        self.token.setObjectName('token')
        self.horizontalLayout_2.addWidget(self.token)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName('label_3')
        self.horizontalLayout_3.addWidget(self.label_3)
        self.subscribers = QtWidgets.QRadioButton(self.layoutWidget)
        self.subscribers.setText('')
        self.subscribers.setChecked(True)
        self.subscribers.setObjectName('subscribers')
        self.horizontalLayout_3.addWidget(self.subscribers)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName('horizontalLayout_4')
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName('label_4')
        self.horizontalLayout_4.addWidget(self.label_4)
        self.blocked = QtWidgets.QRadioButton(self.layoutWidget)
        self.blocked.setEnabled(False)
        self.blocked.setText('')
        self.blocked.setObjectName('blocked')
        self.horizontalLayout_4.addWidget(self.blocked)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 220, 271, 51))
        self.layoutWidget1.setObjectName('layoutWidget1')
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName('horizontalLayout_5')
        self.cancel = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel.sizePolicy().hasHeightForWidth())
        self.cancel.setSizePolicy(sizePolicy)
        self.cancel.setMinimumSize(QtCore.QSize(0, 0))
        self.cancel.setObjectName('cancel')
        self.horizontalLayout_5.addWidget(self.cancel)
        self.continue_2 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.continue_2.sizePolicy().hasHeightForWidth())
        self.continue_2.setSizePolicy(sizePolicy)
        self.continue_2.setMinimumSize(QtCore.QSize(0, 0))
        self.continue_2.setAutoDefault(False)
        self.continue_2.setDefault(True)
        self.continue_2.setObjectName('continue_2')
        self.horizontalLayout_5.addWidget(self.continue_2)
        self.info = QtWidgets.QLabel(self.centralWidget)
        self.info.setGeometry(QtCore.QRect(9, 200, 271, 20))
        self.info.setObjectName('info')
        group.setCentralWidget(self.centralWidget)
        self.retranslateUi(group)
        QtCore.QMetaObject.connectSlotsByName(group)

    def retranslateUi(self, group):
        _translate = QtCore.QCoreApplication.translate
        group.setWindowTitle(_translate('group', 'group'))
        self.groupBox.setTitle(_translate('group', 'Настройки группы'))
        self.label.setText(_translate('group', 'ID'))
        self.label_2.setText(_translate('group', 'Токен*'))
        self.label_3.setText(_translate('group', 'Подписчики'))
        self.label_4.setText(_translate('group', 'Заблокированные*'))
        self.cancel.setText(_translate('group', 'Отмена'))
        self.continue_2.setText(_translate('group', 'Продолжить'))
        self.info.setText(_translate('group', '  * - нужно для импорта бан-листа'))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    group = QtWidgets.QMainWindow()
    ui = Ui_group()
    ui.setupUi(group)
    group.show()
    sys.exit(app.exec_())
