# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(629, 638)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.baseSettings = QtWidgets.QGroupBox(self.centralWidget)
        self.baseSettings.setGeometry(QtCore.QRect(10, 140, 301, 231))
        self.baseSettings.setObjectName("baseSettings")
        self.layoutWidget = QtWidgets.QWidget(self.baseSettings)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 281, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_15.addWidget(self.label_7)
        self.objectType = QtWidgets.QComboBox(self.layoutWidget)
        self.objectType.setObjectName("objectType")
        self.objectType.addItem("")
        self.objectType.addItem("")
        self.horizontalLayout_15.addWidget(self.objectType)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.groupID = QtWidgets.QLineEdit(self.layoutWidget)
        self.groupID.setObjectName("groupID")
        self.horizontalLayout_2.addWidget(self.groupID)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.groupToken = QtWidgets.QLineEdit(self.layoutWidget)
        self.groupToken.setObjectName("groupToken")
        self.horizontalLayout_3.addWidget(self.groupToken)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.userToken = QtWidgets.QLineEdit(self.layoutWidget)
        self.userToken.setObjectName("userToken")
        self.horizontalLayout_4.addWidget(self.userToken)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.chooseFrom = QtWidgets.QComboBox(self.layoutWidget)
        self.chooseFrom.setMinimumSize(QtCore.QSize(140, 0))
        self.chooseFrom.setObjectName("chooseFrom")
        self.chooseFrom.addItem("")
        self.chooseFrom.addItem("")
        self.chooseFrom.addItem("")
        self.chooseFrom.addItem("")
        self.horizontalLayout_5.addWidget(self.chooseFrom)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.blockSettings = QtWidgets.QGroupBox(self.centralWidget)
        self.blockSettings.setEnabled(True)
        self.blockSettings.setGeometry(QtCore.QRect(320, 140, 301, 191))
        self.blockSettings.setObjectName("blockSettings")
        self.layoutWidget1 = QtWidgets.QWidget(self.blockSettings)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 281, 151))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.reason = QtWidgets.QSpinBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reason.sizePolicy().hasHeightForWidth())
        self.reason.setSizePolicy(sizePolicy)
        self.reason.setMinimumSize(QtCore.QSize(105, 0))
        self.reason.setBaseSize(QtCore.QSize(0, 0))
        self.reason.setMaximum(4)
        self.reason.setObjectName("reason")
        self.horizontalLayout_6.addWidget(self.reason)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.period = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.period.sizePolicy().hasHeightForWidth())
        self.period.setSizePolicy(sizePolicy)
        self.period.setMinimumSize(QtCore.QSize(110, 26))
        self.period.setObjectName("period")
        self.period.addItem("")
        self.period.addItem("")
        self.period.addItem("")
        self.period.addItem("")
        self.period.addItem("")
        self.horizontalLayout_7.addWidget(self.period)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.commentVisible = QtWidgets.QCheckBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentVisible.sizePolicy().hasHeightForWidth())
        self.commentVisible.setSizePolicy(sizePolicy)
        self.commentVisible.setText("")
        self.commentVisible.setObjectName("commentVisible")
        self.horizontalLayout_8.addWidget(self.commentVisible)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.comment = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comment.sizePolicy().hasHeightForWidth())
        self.comment.setSizePolicy(sizePolicy)
        self.comment.setMaximumSize(QtCore.QSize(16777215, 39))
        self.comment.setBaseSize(QtCore.QSize(0, 0))
        self.comment.setObjectName("comment")
        self.horizontalLayout_9.addWidget(self.comment)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 450, 611, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chooseUsers = QtWidgets.QPushButton(self.layoutWidget2)
        self.chooseUsers.setEnabled(True)
        self.chooseUsers.setMouseTracking(False)
        self.chooseUsers.setDefault(False)
        self.chooseUsers.setObjectName("chooseUsers")
        self.horizontalLayout.addWidget(self.chooseUsers)
        self.load = QtWidgets.QPushButton(self.layoutWidget2)
        self.load.setEnabled(False)
        self.load.setObjectName("load")
        self.horizontalLayout.addWidget(self.load)
        self.compare = QtWidgets.QPushButton(self.layoutWidget2)
        self.compare.setEnabled(False)
        self.compare.setObjectName("compare")
        self.horizontalLayout.addWidget(self.compare)
        self.applyAction = QtWidgets.QPushButton(self.layoutWidget2)
        self.applyAction.setEnabled(False)
        self.applyAction.setObjectName("applyAction")
        self.horizontalLayout.addWidget(self.applyAction)
        self.proxySettings = QtWidgets.QGroupBox(self.centralWidget)
        self.proxySettings.setGeometry(QtCore.QRect(8, 4, 611, 81))
        self.proxySettings.setObjectName("proxySettings")
        self.layoutWidget3 = QtWidgets.QWidget(self.proxySettings)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 30, 591, 41))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2)
        self.ip = QtWidgets.QLineEdit(self.layoutWidget3)
        self.ip.setObjectName("ip")
        self.horizontalLayout_12.addWidget(self.ip)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_13.addWidget(self.label_6)
        self.port = QtWidgets.QLineEdit(self.layoutWidget3)
        self.port.setObjectName("port")
        self.horizontalLayout_13.addWidget(self.port)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.proxyStatus = QtWidgets.QLabel(self.layoutWidget3)
        self.proxyStatus.setObjectName("proxyStatus")
        self.horizontalLayout_14.addWidget(self.proxyStatus)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 510, 611, 121))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.digitalBar = QtWidgets.QLabel(self.layoutWidget4)
        self.digitalBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.digitalBar.setText("")
        self.digitalBar.setAlignment(QtCore.Qt.AlignCenter)
        self.digitalBar.setObjectName("digitalBar")
        self.horizontalLayout_11.addWidget(self.digitalBar)
        self.help = QtWidgets.QPushButton(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help.sizePolicy().hasHeightForWidth())
        self.help.setSizePolicy(sizePolicy)
        self.help.setMaximumSize(QtCore.QSize(30, 30))
        self.help.setObjectName("help")
        self.horizontalLayout_11.addWidget(self.help)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget4)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.infoBar = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoBar.sizePolicy().hasHeightForWidth())
        self.infoBar.setSizePolicy(sizePolicy)
        self.infoBar.setOpenExternalLinks(True)
        self.infoBar.setObjectName("infoBar")
        self.horizontalLayout_10.addWidget(self.infoBar)
        self.cancel = QtWidgets.QPushButton(self.layoutWidget4)
        self.cancel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel.sizePolicy().hasHeightForWidth())
        self.cancel.setSizePolicy(sizePolicy)
        self.cancel.setMinimumSize(QtCore.QSize(90, 33))
        self.cancel.setMaximumSize(QtCore.QSize(90, 16777215))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_10.addWidget(self.cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.layoutWidget5 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(330, 330, 281, 51))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        self.action = QtWidgets.QComboBox(self.layoutWidget5)
        self.action.setObjectName("action")
        self.action.addItem("")
        self.action.addItem("")
        self.action.addItem("")
        self.action.addItem("")
        self.horizontalLayout_16.addWidget(self.action)
        self.complainSettings = QtWidgets.QToolButton(self.centralWidget)
        self.complainSettings.setGeometry(QtCore.QRect(470, 400, 141, 31))
        self.complainSettings.setObjectName("complainSettings")
        self.layoutWidget6 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 390, 321, 51))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_17.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.changesLabel = QtWidgets.QLabel(self.layoutWidget6)
        self.changesLabel.setObjectName("changesLabel")
        self.horizontalLayout_17.addWidget(self.changesLabel)
        self.changes = QtWidgets.QLabel(self.layoutWidget6)
        self.changes.setObjectName("changes")
        self.horizontalLayout_17.addWidget(self.changes)
        self.check = QtWidgets.QPushButton(self.centralWidget)
        self.check.setGeometry(QtCore.QRect(500, 100, 111, 31))
        self.check.setObjectName("check")
        self.layoutWidget7 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(30, 90, 391, 51))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_18.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.online = QtWidgets.QCheckBox(self.layoutWidget7)
        self.online.setObjectName("online")
        self.horizontalLayout_18.addWidget(self.online)
        self.templates = QtWidgets.QPushButton(self.layoutWidget7)
        self.templates.setObjectName("templates")
        self.horizontalLayout_18.addWidget(self.templates)
        self.clear = QtWidgets.QPushButton(self.layoutWidget7)
        self.clear.setObjectName("clear")
        self.horizontalLayout_18.addWidget(self.clear)
        self.look = QtWidgets.QPushButton(self.centralWidget)
        self.look.setGeometry(QtCore.QRect(340, 400, 113, 31))
        self.look.setObjectName("look")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.baseSettings.setTitle(_translate("MainWindow", "Основные настройки"))
        self.label_7.setText(_translate("MainWindow", "Тип объекта"))
        self.objectType.setToolTip(_translate("MainWindow", "Объект, черный список которого будет изменяться"))
        self.objectType.setItemText(0, _translate("MainWindow", "Группа"))
        self.objectType.setItemText(1, _translate("MainWindow", "Страница"))
        self.label.setText(_translate("MainWindow", "ID группы"))
        self.label_3.setText(_translate("MainWindow", "Токен группы"))
        self.groupToken.setToolTip(_translate("MainWindow", "<html><head/><body><p>Нажмите &quot;?&quot;, чтобы узнать где его взять.</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Токен пользователя"))
        self.userToken.setToolTip(_translate("MainWindow", "<html><head/><body><p>Нажмите &quot;?&quot;, чтобы узнать где его взять.</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Выбрать из"))
        self.chooseFrom.setToolTip(_translate("MainWindow", "Объект, из которого будут выбираться ID пользователей"))
        self.chooseFrom.setItemText(0, _translate("MainWindow", "Группа"))
        self.chooseFrom.setItemText(1, _translate("MainWindow", "Пользователь"))
        self.chooseFrom.setItemText(2, _translate("MainWindow", "Голосование"))
        self.chooseFrom.setItemText(3, _translate("MainWindow", "Другое"))
        self.blockSettings.setTitle(_translate("MainWindow", "Настройки блокировки"))
        self.label_8.setText(_translate("MainWindow", "Причина"))
        self.label_11.setText(_translate("MainWindow", "Срок"))
        self.period.setItemText(0, _translate("MainWindow", "Навсегда"))
        self.period.setItemText(1, _translate("MainWindow", "Год"))
        self.period.setItemText(2, _translate("MainWindow", "Месяц"))
        self.period.setItemText(3, _translate("MainWindow", "Неделя"))
        self.period.setItemText(4, _translate("MainWindow", "День"))
        self.label_9.setText(_translate("MainWindow", "Комментарий виден"))
        self.label_10.setText(_translate("MainWindow", "Комментарий"))
        self.comment.setToolTip(_translate("MainWindow", "<html><head/><body><p>Для более быстрой и стабильной работы оставьте это поле пустым.</p></body></html>"))
        self.chooseUsers.setText(_translate("MainWindow", "Выбрать пользователей"))
        self.load.setText(_translate("MainWindow", "Загрузить"))
        self.compare.setText(_translate("MainWindow", "Сравнение"))
        self.applyAction.setText(_translate("MainWindow", "Заблокировать"))
        self.proxySettings.setTitle(_translate("MainWindow", "Настройки прокси"))
        self.label_2.setText(_translate("MainWindow", "IP адрес"))
        self.ip.setToolTip(_translate("MainWindow", "<html><head/><body><p>Нажмите &quot;?&quot;, чтобы узнать где его взять.</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Порт"))
        self.port.setToolTip(_translate("MainWindow", "<html><head/><body><p>Нажмите &quot;?&quot;, чтобы узнать где его взять.</p></body></html>"))
        self.proxyStatus.setText(_translate("MainWindow", "Не подключено"))
        self.help.setToolTip(_translate("MainWindow", "<html><head/><body><p>Помощь</p></body></html>"))
        self.help.setText(_translate("MainWindow", "?"))
        self.infoBar.setText(_translate("MainWindow", "Получение списка пользователей..."))
        self.cancel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Отменить текущую операцию</p></body></html>"))
        self.cancel.setText(_translate("MainWindow", "Отмена"))
        self.label_12.setText(_translate("MainWindow", "Выберите действие"))
        self.action.setItemText(0, _translate("MainWindow", "Заблокировать"))
        self.action.setItemText(1, _translate("MainWindow", "Разблокировать"))
        self.action.setItemText(2, _translate("MainWindow", "Пожаловаться"))
        self.action.setItemText(3, _translate("MainWindow", "Исключить"))
        self.complainSettings.setText(_translate("MainWindow", "Настройки жалобы"))
        self.changesLabel.setText(_translate("MainWindow", "Уменьшение числа подписчиков на:"))
        self.changes.setText(_translate("MainWindow", "0"))
        self.check.setText(_translate("MainWindow", "Проверить"))
        self.online.setText(_translate("MainWindow", "Online"))
        self.templates.setText(_translate("MainWindow", "Планы работ"))
        self.clear.setToolTip(_translate("MainWindow", "Удалить из списка удаленные и заблокированные странички"))
        self.clear.setText(_translate("MainWindow", "Очистить бан-лист"))
        self.look.setText(_translate("MainWindow", "Посмотреть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

