from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_poll(object):

    def setupUi(self, poll):
        poll.setObjectName('poll')
        poll.resize(301, 356)
        self.centralWidget = QtWidgets.QWidget(poll)
        self.centralWidget.setObjectName('centralWidget')
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 281, 211))
        self.groupBox.setObjectName('groupBox')
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 31, 261, 171))
        self.layoutWidget.setObjectName('layoutWidget')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName('verticalLayout')
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName('label')
        self.horizontalLayout.addWidget(self.label)
        self.ownerID = QtWidgets.QLineEdit(self.layoutWidget)
        self.ownerID.setObjectName('ownerID')
        self.horizontalLayout.addWidget(self.ownerID)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName('label_2')
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ID = QtWidgets.QLineEdit(self.layoutWidget)
        self.ID.setObjectName('ID')
        self.horizontalLayout_2.addWidget(self.ID)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName('label_3')
        self.horizontalLayout_3.addWidget(self.label_3)
        self.answerID = QtWidgets.QLineEdit(self.layoutWidget)
        self.answerID.setObjectName('answerID')
        self.horizontalLayout_3.addWidget(self.answerID)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName('horizontalLayout_5')
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName('label_4')
        self.horizontalLayout_5.addWidget(self.label_4)
        self.wall = QtWidgets.QRadioButton(self.layoutWidget)
        self.wall.setText('')
        self.wall.setChecked(True)
        self.wall.setObjectName('wall')
        self.horizontalLayout_5.addWidget(self.wall)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName('horizontalLayout_4')
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName('label_5')
        self.horizontalLayout_4.addWidget(self.label_5)
        self.discussion = QtWidgets.QRadioButton(self.layoutWidget)
        self.discussion.setText('')
        self.discussion.setObjectName('discussion')
        self.horizontalLayout_4.addWidget(self.discussion)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 290, 241, 61))
        self.layoutWidget1.setObjectName('layoutWidget1')
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName('horizontalLayout_6')
        self.cancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.cancel.setObjectName('cancel')
        self.horizontalLayout_6.addWidget(self.cancel)
        self.continue_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.continue_2.setDefault(True)
        self.continue_2.setObjectName('continue_2')
        self.horizontalLayout_6.addWidget(self.continue_2)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser.setEnabled(False)
        self.textBrowser.setGeometry(QtCore.QRect(10, 230, 281, 51))
        self.textBrowser.setObjectName('textBrowser')
        poll.setCentralWidget(self.centralWidget)
        self.retranslateUi(poll)
        QtCore.QMetaObject.connectSlotsByName(poll)

    def retranslateUi(self, poll):
        _translate = QtCore.QCoreApplication.translate
        poll.setWindowTitle(_translate('poll', 'poll'))
        self.groupBox.setTitle(_translate('poll', 'Настройки голосования'))
        self.label.setText(_translate('poll', 'ID владельца*'))
        self.ownerID.setToolTip(_translate('poll', '<html><head/><body><p>Поставьте &quot;-&quot; перед ID группы</p></body></html>'))
        self.label_2.setText(_translate('poll', 'ID опроса'))
        self.label_3.setText(_translate('poll', 'ID ответа'))
        self.label_4.setText(_translate('poll', 'Опрос на стене'))
        self.label_5.setText(_translate('poll', 'Опрос в обсуждении'))
        self.cancel.setText(_translate('poll', 'Отмена'))
        self.continue_2.setText(_translate('poll', 'Продолжить'))
        self.textBrowser.setHtml(_translate('poll', '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'.SF NS Text\'; font-size:8pt;">* Если владельцом голосования является группа - указывайте &quot;-&quot; перед ID.</span></p></body></html>'))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    poll = QtWidgets.QMainWindow()
    ui = Ui_poll()
    ui.setupUi(poll)
    poll.show()
    sys.exit(app.exec_())
