from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_templates(object):

    def setupUi(self, templates):
        templates.setObjectName('templates')
        templates.resize(415, 265)
        self.centralWidget = QtWidgets.QWidget(templates)
        self.centralWidget.setObjectName('centralWidget')
        self.templatesList = QtWidgets.QListWidget(self.centralWidget)
        self.templatesList.setGeometry(QtCore.QRect(20, 20, 131, 131))
        self.templatesList.setObjectName('templatesList')
        self.apply = QtWidgets.QPushButton(self.centralWidget)
        self.apply.setGeometry(QtCore.QRect(260, 200, 131, 32))
        self.apply.setDefault(False)
        self.apply.setObjectName('apply')
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 180, 221, 71))
        self.layoutWidget.setObjectName('layoutWidget')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName('verticalLayout')
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName('label')
        self.horizontalLayout.addWidget(self.label)
        self.name = QtWidgets.QLineEdit(self.layoutWidget)
        self.name.setObjectName('name')
        self.horizontalLayout.addWidget(self.name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.create = QtWidgets.QPushButton(self.layoutWidget)
        self.create.setObjectName('create')
        self.verticalLayout.addWidget(self.create)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(180, 10, 220, 151))
        self.layoutWidget1.setObjectName('layoutWidget1')
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.delete_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.delete_2.setObjectName('delete_2')
        self.verticalLayout_2.addWidget(self.delete_2)
        self.details = QtWidgets.QPushButton(self.layoutWidget1)
        self.details.setObjectName('details')
        self.verticalLayout_2.addWidget(self.details)
        self.modify = QtWidgets.QPushButton(self.layoutWidget1)
        self.modify.setDefault(False)
        self.modify.setObjectName('modify')
        self.verticalLayout_2.addWidget(self.modify)
        templates.setCentralWidget(self.centralWidget)
        self.retranslateUi(templates)
        QtCore.QMetaObject.connectSlotsByName(templates)

    def retranslateUi(self, templates):
        _translate = QtCore.QCoreApplication.translate
        templates.setWindowTitle(_translate('templates', 'templates'))
        self.apply.setText(_translate('templates', 'Активировать'))
        self.label.setText(_translate('templates', 'Название:'))
        self.create.setText(_translate('templates', 'Создать сборку'))
        self.delete_2.setText(_translate('templates', 'Удалить сборку'))
        self.details.setText(_translate('templates', 'Подробнее о сборке'))
        self.modify.setText(_translate('templates', 'Добавить текущее задание'))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    templates = QtWidgets.QMainWindow()
    ui = Ui_templates()
    ui.setupUi(templates)
    templates.show()
    sys.exit(app.exec_())
